version: 2
jobs:
  node:
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - run:
          name: jest tests
          command: |
            mkdir -p test-results/jest
            yarn run test
      - store_test_results:
          path: test-results
